services:
  - type: web
    name: giftbox-backend
    env: node
    plan: free
    buildCommand: yarn install && yarn prisma generate && yarn run build
    startCommand: yarn start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: giftbox-db
          property: connectionString

databases:
  - name: giftbox-db
    plan: free