services:
  - type: web
    name: giftbox-backend
    env: node
    plan: free
    buildCommand: yarn install && yarn prisma generate && yarn prisma migrate deploy && yarn build
    startCommand: yarn start:prod
    envVars:
      - key: NODE_ENV
        value: production

databases:
  - name: giftbox-db
    plan: free